language: swift
os: osx
osx_image: xcode10

script:
  - xcodebuild -scheme Fornax -workspace Fornax.xcworkspace -destination platform\=iOS\ Simulator,OS\=12.0,name\=iPhone\ X build

before_install:
  - brew update
  - pod install